# SpaceLight
[colors]
# The default text color
foreground = "#b2b2b2"
# The default background color
background = "#292b2e"
# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#e3dedd"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#212026"
# Specifies the border color of the cursor when the cursor style is set to Block,
# of the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#e3dedd"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = "#222222" # untouched

# The color of the split lines between panes
split = "#444444" # untouched

ansi = [
    "#0a0814", 
    "#f2241f", 
    "#67b11d", 
    "#b1951d", 
    "#3a81c3", 
    "#a31db1", 
    "#21b8c7", 
    "#b2b2b2"
]
brights = [
    "#42444a", 
    "#DF201C", 
    "#29A0AD", 
    "#DB742E", 
    "#3980C2", 
    "#2C9473", 
    "#6B3062", 
    "#686868"
]
