#!/bin/sh

# Most convenient numbers in Fibonacci's sequence
gap=5 #21
PANEL_HEIGHT=36
export gap
export PANEL_HEIGHT

#BSPWM configuration
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT+$gap))
bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding $gap #$(($PANEL_HEIGHT+$gap))

for side in top right bottom left; do bspc config ${side}_monocle_padding -$gap; done

#Various settings
bspc config gapless_monocle     true #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
#bspc config paddingless_monocle true
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 

##Color settings
bspc config normal_border_color		"#292B2E"
bspc config active_border_color		"#212026"
bspc config focused_border_color	"#5D4D7A"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

bspc config border_width 3

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#Settings for manual splitting
bspc config split_ratio         0.50

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4

###This creates and names desktops for multiple monitors.
#workspaces_multimonitor &

#Fullscreen applications
bspc rule -a Spotify state=fullscreen

#Floating applications
bspc rule -a kodi state=fullscreen
bspc rule -a feh state=floating
bspc rule -a mpv state=floating sticky=on
bspc rule -a Pavucontrol state=floating sticky=on

#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
#bspc rule -a Xfce4-terminal state=floating

#Tiled applications
bspc rule -a Subl3 state=tiled
bspc rule -a spotify state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
bspc rule -a chromium private=on
bspc rule -a firefox private=on
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled

# For Kwin
bspc rule -a plasmashell     state=floating             sticky=on border=off 
bspc rule -a krunner         state=floating layer=above sticky=on border=off
bspc rule -a lattedock       state=floating border=off center=off
bspc rule -a latte-dock      state=floating border=off center=off
bspc rule -a Plasma          state=floating
bspc rule -a plasma-desktop  state=floating
bspc rule -a Kmix            state=floating
bspc rule -a Klipper         state=floating
bspc rule -a KRuler          state=floating
bspc rule -a Plasmoidviewer  state=floating
bspc rule -a '*:plasma'      state=floating
bspc rule -a '*:plasmashell' state=floating

#open applications on specific workspaces
#bspc rule -a Steam desktop='^5'

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command $HERE/scripts/adjust-new-window
#fix for moving spotify to specific workspace
#bspc config external_rules_command $HERE/scripts/external_rules_command


# bspc config external_rules_command ~/.config/bspwm/scripts/on_monocle.sh &

xdo raise -N lattedock

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [[ "$state" != fullscreen ]]; then continue; fi
    if [[ "$flag" == on ]]; then
        xdo lower -N lattedock
    else
        xdo raise -N lattedock
    fi
done &


#xprop -root -f _NET_DESKTOP_LAYOUT 32cccc -set _NET_DESKTOP_LAYOUT 1,1,10,0 &

# https://github.com/sumeet/golden/blob/master/golden.py
#~/.config/bspwm/scripts/golden/run.sh &
