#!/usr/bin/env bash

dawn=$(cat /tmp/sway-colord/dawn)
dusk=$(cat /tmp/sway-colord/dusk)
now=$(date +%H:%M)

if [[ "$now" < "$dawn" ]] || [[ "$now" > "$dusk" ]];; then
    # Dark Theme
    /usr/bin/btm -C ~/.config/bottom/space_dark.toml
else
    # Light Theme
    /usr/bin/btm -C ~/.config/bottom/space_light.toml
fi

