#!/usr/bin/env bash

dawn=$(cat /tmp/sway-colord/dawn)
dusk=$(cat /tmp/sway-colord/dusk)
now=$(date +%H:%M)

if [[ "$now" < "$dawn" ]] || [[ "$now" > "$dusk" ]]; then
    # Dark Theme
    /usr/bin/wofi --conf ~/.config/wofi/config -s ~/.config/wofi/space_dark.css
else
    # Light Theme
    /usr/bin/wofi --conf ~/.config/wofi/config -s ~/.config/wofi/space_light.css
fi

