#!/usr/bin/env bash

dawn=$(cat /tmp/sway-colord/dawn)
dusk=$(cat /tmp/sway-colord/dusk)
now=$(date +%H:%M)

if [[ "$now" < "$dawn" ]] || [[ "$now" > "$dusk" ]];; then
    # Dark Theme
    /usr/bin/gitui -t space_dark.ron
else
    # Light Theme
    /usr/bin/gitui -t space_light.ron
fi

