#!/usr/bin/env bash

dawn=$(cat /tmp/sway-colord/dawn)
dusk=$(cat /tmp/sway-colord/dusk)
now=$(date +%H:%M)

if [[ "$now" < "$dawn" ]] || [[ "$now" > "$dusk" ]]; then
    # Dark Theme
    /usr/bin/nwggrid -wm sway -n 8 -b 222226 -c space-dark.css
else
    # Light Theme
    /usr/bin/nwggrid -wm sway -n 8 -b e7e5eb -c space-light.css 
fi

