#!/usr/bin/env bash

dawn=$(cat /tmp/sway-colord/dawn)
dusk=$(cat /tmp/sway-colord/dusk)
now=$(date +%H:%M)

if [[ "$now" < "$dawn" ]] || [[ "$now" > "$dusk" ]]; then
    # Dark Theme
    /usr/bin/nwgbar -c ~/.config/nwg-launchers/nwgbar/space-dark.css -wm sway
else
    # Light Theme
    /usr/bin/nwgbar -c ~/.config/nwg-launchers/nwgbar/space-light.css -wm sway
fi

