#!/bin/bash

H=$(date  "+%k")
DAWN=7
DUSK=19

# If time is between 7AM & 7PM
if (( DAWN <= H && DUSK > H )); then
    # Light theme
    /usr/bin/nwgbar -c ~/.config/nwg-launchers/nwgbar/space-light.css -wm sway
else
    # Dark theme
    /usr/bin/nwgbar -c ~/.config/nwg-launchers/nwgbar/space-dark.css -wm sway
fi
