#!/bin/bash
# Convert all files in directory
cvrt() {
	av() {
		if command -v ffmpeg &> /dev/null; then
			if [[ -n "$1" && -n "$2" && -n "$3" ]]; then
				eval "fd -e $1 -x ffmpeg -i {} $2 {.}.$3"
				fd -e $1 -x rm {}
			else
				echo "incorrect number of arguements"
			fi
		else
			echo "Please install ffmpeg to convert $1 to $3"
			return 1
		fi
	}

	img() {
		if command -v convert &> /dev/null; then
			if [[ -n "$1" && -n "$2" ]]; then
				eval "fd -e $1 -x convert {} {}.$2"
				fd -e $1 -x rm {}
			else
				echo "incorrect number of arguements"
			fi
		else
			echo "Please install ImageMagick to convert $1 to $3"
			return 1
		fi
	}

	if [[ -n "$1" && -n "$2" ]]; then
		if ! command -v fd &> /dev/null; then
			echo "Please install fd"
			return 1
		fi

		FROM=$1
		TO=$2
		
		case $FROM in
		avi)
			case $TO in
			mp4)
				av $FROM "-c:v copy -c:a copy -y" $TO
				;;
			mpeg)
				av $FROM "-target pal-dvd -ps 2000000000 -aspect 16:9" $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		flac)
			case $TO in
			opus)
				av $FROM "-c:a libopus" $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		flv)
			case $TO in
			mp4)
				av $FROM "-c:v libx264" $TO
				;;
			mpeg)
				av $FROM " " $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		jpg)
			case $TO in
			png | webp)
				img $FROM $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		mkv)
			case $TO in
			mp4)
				av $FROM "-strict experimental -map 0:0 -map 0:1 -c:v copy -c:a:1 libmp3lame -b:a 192k -ac 6" $TO
				;;
			png)
				av $FROM "-codec copy" $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		mp3)
			case $TO in
			wav)
				av $FROM "-acodec pcm_s16le -ac 1 -ar 22050" $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		mp4)
			case $TO in
			avi)
				av $FROM " " $TO
				;;
			mp3)
				av $FROM "-vn -ar 44100 -ac 2 -ab 320k -f mp3" $TO
				;;
			webm)
				av $FROM "-f webm -c:v libvpx -b:v 1M -acodec libvorbis" $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		mpg)
			case $TO in
			flv)
				av $FROM "-ab 26k -f flv" $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		png)
			case $TO in
			jpg | webp)
				img $FROM $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		webm)
			case $TO in
			mp3)
				av $FROM "-vn -ar 44100 -ac 2 -ab 320k -f mp3" $TO
				;;
			mp4)
				av $FROM "-qscale 0" $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		webp)
			case $TO in
			jpg | png)
				img $FROM $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		wmv)
			case $TO in
			mp4)
				av $FROM "-c:v libx264 -preset ultrafast" $TO
				;;
			*)
				echo "Converting from $TO to $FROM is not currently supported"
				;;
			esac
			;;
		*)
			echo "Converting from $TO is not currently supported"
			;;
		esac
	else
		echo "usage: convert <filetypes that need to be converted> <filetype that you want them converted to>"
		return 1
	fi
}
