#!/bin/bash
# Goes up many dirs as the number passed as argument, if none goes up by 1 by default
up() {
	local d=""
		limit=$1
		for ((i=1 ; i <= limit ; i++)); do
			d=$d/..
				done
				d=$(echo $d | sed 's/^\///')
				if [[ -z "$d" ]]; then
					d=..
						fi
						cd $d
}
