#!/bin/bash
ngx(){
    local conf="/etc/nginx/nginx.conf"
    local sites_en="/etc/nginx/sites-enabled"
    local sites_av="/etc/nginx/sites-available"
    bd="$PWD"
    usage(){
        echo "\e[33mUSAGE:\e[39m"
        echo "    ngx [FLAGS]\n"
        echo "\e[33mFLAGS:\e[39m"
        echo "    \e[32m-h\e[39m, \e[32m--help\e[39m        Prints help information"
        echo "    \e[32m-c\e[39m, \e[32m--conf\e[39m        Edit nginx.conf"
        echo "    \e[32m-e\e[39m, \e[32m--enabled\e[39m     Enable a site from sites-available"
        echo "    \e[32m-r\e[39m, \e[32m--reload\e[39m      Reloads nginx"
        echo "    \e[32m-s\e[39m, \e[32m--site\e[39m        Edit a site from sites-available"
        return 1
    }
    reload(){
        sudo nginx -t && sudo systemctl restart nginx
    }
    conf(){
        sudo -E nvim $conf
    }
    sites_avail(){
        pushd $sites_av
        if hash sk 2>/dev/null; then
            if hash bat 2>/dev/null; then
                sudo -E nvim -- $sites_av/$(fd --search-path=$sites_av -x echo {/} | sk --ansi --preview 'bat --color=always -l scss --style=header,grid --line-range :300 {}' --preview-window 'right:70%')
            else
                sudo -E nvim -- $sites_av/$(fd --search-path=$sites_av -x echo {/} | sk --preview="cat {}" --preview-window=right:70%:wrap)
            fi
            elif hash fzf 2>/dev/null; then
            if hash bat 2>/dev/null; then
                sudo -E nvim -- $sites_av/$(fd --search-path=$sites_av -x echo {/} | fzf --ansi --preview 'bat --color=always -l scss --style=header,grid --line-range :300 {/}' --preview-window 'right:70%')
            else
                sudo -E nvim -- $sites_av/$(fd --search-path=$sites_av -x echo {/} | fzf --preview="cat {}" --preview-window=right:70%:wrap)
            fi
        else
            ls "$sites_av"
        fi
        popd $sites_av
        cd $bd
    }
    sites_en(){
        pushd $sites_av/
        if hash sk 2>/dev/null; then
            site=($sites_av/$(fd --search-path=$sites_av -a -x echo {/} | sk --ansi  --preview="if [ -f $sites_en/{/} ];then echo '\e[32mEnabled\e[39m'; else echo '\e[31mDisabled\e[39m'; fi" --preview-window 'right:70%'))
            if [ -f $sites_en/$(basename $site) ];then
                sudo rm $sites_en/$(basename $site)
            else
                sudo ln -s $site $sites_en/$(basename $site)
            fi
            elif hash fzf 2>/dev/null; then
            site=($sites_av/$(fd --search-path=$sites_av -a -x echo {/} | fzf --ansi --preview="if [ -f $sites_en/{/} ];then echo '\e[32mEnabled\e[39m'; else echo '\e[31mDisabled\e[39m'; fi" --preview-window 'right:70%'))
            if [ -f $sites_en/$(basename $site) ];then
                sudo rm $sites_en/$(basename $site)
            else
                sudo ln -s $site $sites_en/$(basename $site)
            fi
        else
            ls "$sites_en"
        fi
        popd $sites_av/
        cd $bd
    }
    
    case $1 in
        -c | --conf )
            conf
        ;;
        -e | --enabled )
            sites_en
        ;;
        -r | --reload )
            reload
        ;;
        -s | --site )
            sites_avail
        ;;
        *)
            usage
    esac
}
