#!/bin/bash
ext() {
  ext-all --exclude .git --exclude target --exclude "*.log"
}
ext-all() {
  local name=$(basename $(pwd))
  cd ..
  tar -cvzf "$name.tgz" $* --exclude "$name.tgz" "$name"
  cd -
  mv ../"$name".tgz .
}
