#!/usr/bin/env bash

red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
bprp="\e[35;1m"
rst="\e[0m"

heart_f=""
heart_half="ﯜ"
heart_e=""

fg="\e[31m"

bat_status=""
bat_status=$( cat /sys/class/power_supply/BATT/capacity )
charging_status=$( cat /sys/class/power_supply/BATT/status )

health() {
    half=0
    full=$(( $bat_status/20 ))
    
    if [[ $(( $bat_status%20 )) -ge 15 ]]; then
        full=$(( $full + 1 )) 
    elif [[ $(( $bat_status%20 )) -ge 7 ]]; then
        half=$(( $half + 1 )) 
    fi
    empty=$(( 5 - $full - $half ))

    for (( c=1; c<=$full; c++ )); do
        echo -ne "${heart_f} "
    done
    if (( $half > 0 )); then
        echo -ne "${heart_half} "
    fi
    for (( c=1; c<=$empty; c++ )); do        
        echo -ne "${heart_e} "    
    done
    echo
}

bat_status_small() {
    if [[ "$charging_status" = *Charging* ]]; then
        echo -ne "+$bat_status%"
    else
        echo -ne "$bat_status%"
    fi
}

[ -z "$1" ] && {
    bat_status_small
}

while getopts qi options 
do
    case $options in
        i)
            bat_status_small
            ;;
        q)
            if [[ "$charging_status" = *Charging* ]]; then
                echo -ne "+ $(health)"
            else
                health
            fi
    esac
done
