#!/bin/bash

s=$(< /proc/uptime)
s=${s/.*}

d="$((s / 60 / 60 / 24))"
h="$((s / 60 / 60 % 24))"
m="$((s / 60 % 60))"

# Hide empty fields.
((${d/ *} == 0)) && unset d
((${h/ *} == 0)) && unset h
((${m/ *} == 0)) && unset m

uptime=${d:+$d,d}${h:+$h,h}${m:+$m,m}
uptime=${uptime%', '}
uptime=${uptime:-$s seconds}
uptime=${uptime//,}

echo $uptime