-- vim-Abolish("like functionality
local Abolish= require("utils").abolish

Abolish("Tqbf", "The quick, brown fox jumps over the lazy dog")
Abolish(
    "Lidsa",
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"
)
Abolish("scflead", "supercalifragilisticexpialidocious")
--------------
--     ___  --
--    /   | --
--   / /| | --
--  / ___ | --
-- /_/  |_| --
--------------
Abolish("alot", "a lot")
Abolish("about{a,it,the}", "about {}")
Abolish("abreviat{ed,ion}", "abbreviat{}")
Abolish("abscence", "absence")
Abolish("accesories", "accessories")
Abolish("accidant", "accident")
Abolish("accomodat{e,ed,es,ing,ion,ions}", "accommodat{}")
Abolish("accommodat{e,ed,es,ing,ion,ions}", "accommodat{}")
Abolish("accomdat{e,ed,es,ing,ion,ions}", "accommodat{}")
Abolish("accomadat{e,ed,es,ing,ion,ions}", "accommodat{}")
Abolish("accommadat{e,ed,es,ing,ion,ions}", "accommodat{}")
Abolish("accordingto", "according to")
Abolish("acheiv{e,ed,ing}", "achiev{}")
Abolish("aquisitio{n,ns}", "acquisition{}")
Abolish("accross", "across")
Abolish("adequi{t,te}", "adequate")
Abolish("advanage", "advantage")
Abolish("asdvertising", "advertising")
Abolish("affraid", "afraid")
Abolish("afterthe", "after the")
Abolish("afterword{d,ds}", "afterward{}")
Abolish("aganist", "against")
Abolish("againstt he", "against the")
Abolish("agree{m,mee}net", "agreement")
Abolish("agree{m,mee}nt", "agreement")
Abolish("agree{m,mee}nets", "agreements")
Abolish("agree{m,mee}nts", "agreements")
Abolish("alr{aedy,eayd,eday}", "already")
Abolish("ameria", "America")
Abolish("adn", "and")
Abolish("anbd", "and")
Abolish("andone", "and one")
Abolish("andt{eh,he}", "and the")
Abolish("anual", "annual")
Abolish("anomol{y,ies}", "anomal{}")
Abolish("anothe", "another")
Abolish("appartment", "apartment")
Abolish("appar{ant,rent}", "apparent")
Abolish("appearence", "appearance")
Abolish("appeares", "appears")
Abolish("appndind", "appending")
Abolish("applicaito{n,ns}", "application{}")
Abolish("applyed", "applied")
Abolish("appointiment", "appointment")
Abolish("approrp{r,}iate", "appropriate")
Abolish("achive", "archive")
Abolish("arguement", "argument")
Abolish("arguements", "arguments")
Abolish("arond", "around")
Abolish("artic{a,e}l", "article")
Abolish("as{the,well}", "as {}")
Abolish("assignemtn", "assignment")
Abolish("assistent", "assistant")
Abolish("atthe", "at the")
Abolish("atmospher", "atmosphere")
Abolish("aud{ei,ia}nce", "audience")
Abolish("austrail{a,an,ia}", "australia")
Abolish("austrailian", "australian")
---------------
--     ____  --
--    / __ ) --
--   / __  | --
--  / /_/ /  --
-- /_____/   --
---------------
Abolish("b{akc,cak}", "back")
Abolish("bal{e,la}nce", "balance")
Abolish("bve", "be")
Abolish("beutiful", "beautiful")
Abolish("because{a,of,the,you}", "because {}")
Abolish("be{cuse,cuase,acuse,casue,caus}", "because")
Abolish("becom{e,m}ing", "becoming")
Abolish("befoer", "before")
Abolish("beg{gin,in,inin}ing", "beginning")
Abolish("belei{ve,f,ve,ved,ves}", "belie{}")
Abolish("beleie{v,ve}", "belie{}")
Abolish("benifi{t,ts}", "benefi{}")
Abolish("bernouilli", "bernoulli")
Abolish("betwen", "between")
Abolish("blase", "blasé")
Abolish("blitzkreig", "Blitzkrieg")
Abolish("bonnano", "Bonanno")
Abolish("boxs", "boxes")
Abolish("brasillian", "Brazilian")
Abolish("britian", "Britain")
Abolish("brittish", " British")
Abolish("brodcast", "broadcast")
Abolish("boroken", "broken")
Abolish("buddah", "Buddha")
Abolish("buddist", "Buddhist")
Abolish("butthe", "but the")
---------------
--    ______ --
--   / ____/ --
--  / /      --
-- / /___    --
-- \____/    --
---------------
Abolish("cafe", "café")
Abolish("cafeine", "caffeine")
Abolish("cal{cul,u}lated", "calculated")
Abolish("calande{r,rs}", "calenda{}")
Abolish("calaende{r,rs}", "calenda{}")
Abolish("cambrige", "Cambridge")
Abolish("acn", "can")
Abolish("cna", "can")
Abolish("cxan", "can")
Abolish("candidta{e,es}", "candidat{}")
Abolish("capetown", "Cape Town")
Abolish("carmalite", "Carmelite")
Abolish("carraig{e,es}", "carriage{}")
Abolish("carnagie", "Carnegie")
Abolish("carnigie", "Carnegie")
Abolish("carribbean", "Caribbean")
Abolish("carribean", "Caribbean")
Abolish("carthagian", "Carthaginian")
Abolish("catagor{y,ies}", "categor{}")
Abolish("ctaegory", "category")
Abolish("cataline", "Catiline")
Abolish("cieling", "ceiling")
Abolish("ceasar", "Caesar")
Abolish("celcius", "Celsius")
Abolish("certian", "certain")
Abolish("challang{e,es}", "challeng{}")
Abolish("chnag{e,ing,er,es}", "chang{}")
Abolish("chanegs", "changes")
Abolish("chaneg", "change")
Abolish("changable", "changeable")
Abolish("cha{ngeing,ngng,ging}", "changing")
Abolish("chaging", "changing")
Abolish("caharcter", "character")
Abolish("charac{hter,tor,ter}", "character")
Abolish("charac{hter,tor,ter}s", "characters")
Abolish("charec{hter,tor,ter}", "character")
Abolish("charec{hter,tor,ter}s", "characters")
Abolish("chekc", "check")
Abolish("chekcs", "checks")
Abolish("cheif{f,fs}", "chie{}")
Abolish("cincinatti", "Cincinnati")
Abolish("circut", "circuit")
Abolish("sercumstances", "circumstances")
Abolish("clae{r,red,rly}", "clea{}")
Abolish("cliche", "cliché")
Abolish("cliant", "client")
Abolish("colection", "collection")
Abolish("combintatio{n,ns}", "combinatio{}")
Abolish("comming", "coming")
Abolish("commadn", "command")
Abolish("committmen{t,ts}", "commitmen{}")
Abolish("comit{ed,ee}", "committ{}")
Abolish("comitt{ment,ments}", "commit{}")
Abolish("commit{ee,te,ty}", "committee")
Abolish("comunicat{e,es,ion,ions}", "communicat{}")
Abolish("comunit{y,ies}", "communit{}")
Abolish("comapn{y,ies}", "compan{}")
Abolish("coman{y,ies}", "compan{}")
Abolish("compair", "compare")
Abolish("{compar,compari}sion", "comparison")
Abolish("complet{ly,ness}", "complete{}")
Abolish("compleat{ed,ely,ness}", "complet{}")
Abolish("composate", "composite")
Abolish("condolances", "condolences")
Abolish("conneticut", "Connecticut")
Abolish("conferance", "conference")
Abolish("confirmmation", "confirmation")
Abolish("conect{,s,ed,ion,ions}", "connect{}")
Abolish("considerit{,e}", "considerate")
Abolish("consistan{cy,cies,t,tly}", "consisten{}")
Abolish("inconsistan{cy,cies,t,tly}", "inconsisten{}")
Abolish("consonent", "consonant")
Abolish("conspiricy", "conspiracy")
Abolish("consulten{t,ts}", "consultan{}")
Abolish("comntain{n,ns}", "contai{}")
Abolish("comtai{n,ns}", "contai{}")
Abolish("convertabl{e,es}", "convertibl{}")
Abolish("coop{a,o}rate", "cooperate")
Abolish("cpoy", "copy")
Abolish("corproatio{n,ns}", "corporatio{}")
Abolish("corruptable", "corruptible")
Abolish("cotten", "cotton")
Abolish("coudl", "could")
Abolish("couldthe", "could the")
Abolish("couldnt", "couldn’t")
Abolish("creme", "crème")
Abolish("cu{sot,tso}mer", "customer")
Abolish("cu{sot,tso}mers", "customers")
---------------
--     ____  --
--    / __ \ --
--   / / / / --
--  / /_/ /  --
-- /_____/   --
---------------
Abolish("danceing", "dancing")
Abolish("dardenelles", "Dardanelles")
Abolish("desi{c,s}ion", "decision")
Abolish("desi{c,s}ions", "decisions")
Abolish("deciso{n,ns}", "decisio{}")
Abolish("decor", "décor")
Abolish("defendent{t,ts}", "defendant{}")
Abolish("definately", "definitely")
Abolish("definitly", "definitely")
Abolish("delimete{r,rs}", "delimiter{}")
Abolish("deptartment", "department")
Abolish("disign", "design")
Abolish("despara{te,tely,tion}", "despera{}")
Abolish("deatils", "details")
Abolish("detente", "détente")
Abolish("devellop{ed,er,ers,ing,ment,ments,s}", "develop{}")
Abolish("devellope{ed,er,ers,ing,ment,ments,s}", "develop{}")
Abolish("develeop{,ed,er,ers,ing,ment,ments,s}", "develop{}")
Abolish("develeope{ed,er,ers,ing,ment,ments,s}", "develop{}")
Abolish("developo{r,rs}", "develope{}")
Abolish("develeoprs", "developers")
Abolish("develpmen{t,ts}", "developmen{}")
Abolish("didnot", "did not")
Abolish("dijktra", "Dijkstra")
Abolish("ddi", "did")
Abolish("didint", "didn’t")
Abolish("difefran{t,ce,ces}", "differen{}")
Abolish("differan{t,ce,ces}", "differen{}")
Abolish("difefren{t,ce,ces}", "differen{}")
Abolish("differen{t,ce,ces}", "differen{}")
Abolish("differemt", "different")
Abolish("diff{er,re}nt", "different")
Abolish("directiosn", "direction")
Abolish("directer{r,rs}", "directo{}")
Abolish("discoverd", "discovered")
Abolish("descrepenc{y,ies}", "discrepanc{}")
Abolish("discrepenc{y,ies}", "discrepanc{}")
Abolish("discrepenc{y,ies}", "discrepanc{}")
Abolish("discrepanc{y,ies}", "discrepanc{}")
Abolish("diaplay", "display")
Abolish("dispaly", "display")
Abolish("disatisfied", "dissatisfied")
Abolish("dissonent", "dissonant")
Abolish("distribusio{n,ns}", "distributio{}")
Abolish("divsion", "division")
Abolish("docu{ement,emnt,metn,mnet}", "document")
Abolish("docu{ement,emnt,metn,mnet}s", "document{}s")
Abolish("dcumen{t,ts,tation}", "document{}")
Abolish("doese", "does")
Abolish("doesnt", "doesn’t")
Abolish("do{nig,ign,img,ind}", "doing")
Abolish("dollers", "dollars")
Abolish("dont", "don’t")
Abolish("dont", "don't")
Abolish("dravadian", "Dravidian")
Abolish("drnik", "drink")
Abolish("driveing", "driving")
-- E
Abolish("eclair", "éclair")
Abolish("effecient", "efficient")
Abolish("efor{t,ts}", "effor{}")
Abolish("eligable", "eligible")
Abolish("esle", "else")
Abolish("embaras{s,sing,sed,ses}", "embarras{}")
Abolish("emigre", "émigré")
Abolish("enlish", "English")
Abolish("enought", "enough")
Abolish("entree", "entrée")
Abolish("equippment", "equipment")
Abolish("equivalant", "equivalent")
Abolish("espe{cally,cialyl,sially}", "especially")
Abolish("etx", "etc")
Abolish("euphamis{m,ms,tic,tically}", "euphemis{}")
Abolish("eur{opi,pe,poe,e}an", "European")
Abolish("eur{opi,pe,poe,e}ans", "Europeans")
Abolish("everytime", "every time")
Abolish("excellant", "excellent")
Abolish("ex{chagn,hcang}", "exchange")
Abolish("ex{chagn,hcang}es", "exchanges")
Abolish("excitment", "excitement")
Abolish("excercise", "exercise")
Abolish("existan{ce,t}", "existen{}")
Abolish("exprienc{e,ed}", "experienc{}")
Abolish("experianc{e,es,ed}", "experienc{}")
Abolish("experiancing", "experiencing")
-- F
Abolish("facade", "façade")
Abolish("farenheit", "Fahrenheit")
Abolish("familai{r,rize,rized,rized,rizing}", "familia{}")
Abolish("famila{r,rize,rized,rized,rizing}", "familia{}")
Abolish("famillia{r,rize,rized,rized,rizing}", "familia{}")
Abolish("familia{r,rize,rized,rized,rizing}", "familia{}")
Abolish("fammilai{r,rize,rized,rized,rizing}", "familia{}")
Abolish("fammila{r,rize,rized,rized,rizing}", "familia{}")
Abolish("fammillia{r,rize,rized,rized,rizing}", "familia{}")
Abolish("fammilia{r,rize,rized,rized,rizing}", "familia{}")
Abolish("favoritted", "favourited")
Abolish("faetur{e,es}", "featur{}")
Abolish("feb{u,ur}ary", "February")
Abolish("efel", "feel")
Abolish("fwe", "few")
Abolish("feil{d,ds}", "fiel{}")
Abolish("fianlly", "finally")
Abolish("finalyl", "finally")
Abolish("fidn", "find")
Abolish("firts", "first")
Abolish("flemmish", "Flemish")
Abolish("follwo{,ing}", "follow{}")
Abolish("for{a,the}", "for {}")
Abolish("foriegn", "foreign")
Abolish("formalhaut", "Fomalhaut")
Abolish("forwr{d,ds,ding,der,dmost}", "forwar{}")
Abolish("fowar{d,ds,ding,der}", "forwar{}")
Abolish("foudn", "found")
Abolish("fransisca{n,ns}", "Francisca{}")
Abolish("frein{d,dly,ds}", "frien{}")
Abolish("firends", "friends")
Abolish("frmo", "from")
Abolish("fromthe", "from the")
Abolish("frmo", "from")
Abolish("furneral", "funeral")
-- G
Abolish("galations", "Galatians")
Abolish("gameboy", "Game Boy")
Abolish("gemeral", "general")
Abolish("get{ing,tin}", "getting")
Abolish("ghandi", "Gandhi")
Abolish("gievn", "given")
Abolish("giveing", "giving")
Abolish("gloabl", "global")
Abolish("godounov", "Godunov")
Abolish("go{ign,nig}", "going")
Abolish("oging", "going")
Abolish("gothenberg", "Gothenburg")
Abolish("gottleib", "Gottlieb")
Abolish("gove{n,r}ment", "government")
Abolish("gerat", "great")
Abolish("gruo{p,ps}", "grou{}")
Abolish("grwo", "grow")
Abolish("garantee", "guarantee")
Abolish("gaurd", "guard")
Abolish("guatamal{a,an}", "Guatemal{}")
Abolish("guidlines", "guidelines")
Abolish("guili{a,o}", "Giuli{}")
Abolish("guiness", "Guinness")
Abolish("guiseppe", "Giuseppe")
-- H
Abolish("habsbourg", "Habsburg")
Abolish("hadbeen", "had been")
Abolish("hda", "had")
Abolish("ahppen", "happen")
Abolish("hape{n,ned,ning,ns}", "happe{}")
Abolish("happend", "happened")
Abolish("hallowean", "Halloween")
Abolish("{has,have}been", "{} been")
Abolish("hsa", "has")
Abolish("hasnt", "hasn’t")
Abolish("hva{e,ing}", "hav{}")
Abolish("ahve", "have")
Abolish("haev", "have")
Abolish("hve", "have")
Abolish("haveing", "having")
Abolish("havin  ", "having")
Abolish("he{said,was}", "he {}")
Abolish("hge", "he")
Abolish("hearign", "hearing")
Abolish("herat", "heart")
Abolish("heidelburg", "Heidelberg")
Abolish("hlep", "help")
Abolish("helpfull", "helpful")
Abolish("hense ", "hence")
Abolish("ehr", "her")
Abolish("hightlight", "highlight")
Abolish("hismelf", "himself")
Abolish("hsi", "his")
Abolish("ihs", "his")
Abolish("honsetly", "honestly")
Abolish("httpL", "http:")
-- I
Abolish("I{have,am,was}", "I {}")
Abolish("idae", "idea")
Abolish("idaes", "ideas")
Abolish("identofy", "identify")
Abolish("Im", "I'm")
Abolish("imediate", "immediate")
Abolish("imediatly", "immediately")
Abolish("immediatly", "immediately")
Abolish("implimen{t,ts,ting,ted,tation}", "implemen{}")
Abolish("importen{t,tly}", "importan{}")
Abolish("importna{t,tly}", "importan{}")
Abolish("impossable", "impossible")
Abolish("improvemn{t,ts}", "improvemen{}")
Abolish("improvmen{t,ts}", "improvemen{}")
Abolish("improvmen{t,ts}", "improvemen{}")
Abolish("inteh", "in the")
Abolish("in{which,the,face}", "in {}")
Abolish("includ", "include")
Abolish("indenpenden{ce,t}", "independen{}")
Abolish("independan{ce,t}", "independen{}")
Abolish("indepedent", "independent")
Abolish("indecate", "indicate")
Abolish("influance", "influence")
Abolish("infomation", "information")
Abolish("informatoin", "information")
Abolish("inheran{t,tly}", "inheren{}")
Abolish("inital", "initial")
Abolish("irreleven{ce,cy,t,tly}", "relevan{}")
Abolish("ititial", "initial")
Abolish("isntall", "install")
Abolish("instaleld", "installed")
Abolish("insted", "instead")
Abolish("insurence", "insurance")
Abolish("itneres{t,ted,tint,ts}", "interest{}")
Abolish("interum", "interim")
Abolish("is{the,is,was}", "is {}")
Abolish("ihaca", "Ithaca")
Abolish("israelies", "Israelis")
-- J
Abolish("januray", "January")
Abolish("japanes", "Japanese")
Abolish("jugment", "judgment")
Abolish("jospeh", "Joseph")
Abolish("jua{d,da}ism", "Judaism")
Abolish("jsut", "just")
-- K
Abolish("kon{w,wn,ws}", "kno{}")
Abolish("knwo{n,s}", "know{}")
Abolish("nkow", "know")
Abolish("knowl{d,e}ge", "knowledge")
-- L
Abolish("labratory", "laboratory")
Abolish("lastyear", "last year")
Abolish("lastest", "latest")
Abolish("learnign", "learning")
Abolish("lenght", "length")
Abolish("lessio{n,ns}", "lesso{}")
Abolish("ltters", "letters")
Abolish("levle", "level")
Abolish("lib{ary,arry,rery}", "library")
Abolish("lisense", "license")
Abolish("lieutenent", "lieutenant")
Abolish("li{uke,iek}", "like")
Abolish("liekd", "liked")
Abolish("likly", "likely")
Abolish("littel", "little")
Abolish("litttle", "little")
Abolish("liev", "live")
Abolish("liveing", "living")
Abolish("lonly", "lonely")
Abolish("lookign", "looking")
Abolish("loev", "love")
Abolish("lybia", "Libya")
-- M
Abolish("amde", "made")
Abolish("mantain", "maintain")
Abolish("maintenence", "maintenance")
Abolish("mka{e,es,ing}", "mak{}")
Abolish("amke", "make")
Abolish("amkes", "makes")
Abolish("makeing", "making")
Abolish("malcom", "Malcolm")
Abolish("managment", "management")
Abolish("marie", "Marie")
Abolish("marraig{e,es}", "marriag{}")
Abolish("massachusse{t,tt}s", "Massachusetts")
Abolish("mediteranean", "Mediterranean")
Abolish("memeber", "member")
Abolish("merchent", "merchant")
Abolish("mesag{e,es}", "messag{}")
Abolish("michagan", "Michigan")
Abolish("missisi{p,pp}i", "Mississippi")
Abolish("mispel{l,ling,lings,led,ls}", "misspel{}")
Abolish("misouri", "Missouri")
Abolish("moeny", "money")
Abolish("monserrat", "Montserrat")
Abolish("montnana", "Montana")
Abolish("{mro,omr}e", "more")
Abolish("morgage", "mortgage")
Abolish("mo{r,rr}isette", "Morissette")
Abolish("myu", "my")
Abolish("mysefl", "myself")
Abolish("mythraic", "Mithraic")
-- N
Abolish("naive", "naïve")
Abolish("napoleonian", "Napoleonic")
Abolish("nazereth", "Nazareth")
Abolish("nec{ce,ces,e,ass,cess,es}sary", "necessary")
Abolish("nec{ce,ces,e,ass,cess,es}sary", "necessarily")
Abolish("ne{cecs,secc}ary", "necessary")
Abolish("negotiaing", "negotiating")
Abolish("nver", "never")
Abolish("foundland", "Newfoundland")
Abolish("newyorker", "New Yorker")
Abolish("nothign", "nothing")
Abolish("nw{o,e}", "n{}w")
Abolish("nullabour", "Nullarbor")
Abolish("nuremburg", "Nuremberg")
Abolish("nonexistan{ce,t}", "nonexisten{}")
-- O
Abolish("obediant", "obedient")
Abolish("ocasion", "occasion")
Abolish("occassion", "occasion")
Abolish("ocu{r,red,rence}", "occur{r,red,rence}")
Abolish("occu{r,red,rence}", "occur{r,red,rence}")
Abolish("of{its,the}", "of {}")
Abolish("one{of,point}", "one {}")
Abolish("onyl", "only")
Abolish("opne", "open")
Abolish("opperation", "operation")
Abolish("oeprator", "operator")
Abolish("oppotunit{y,ies}", "opp{or}tunit{}")
Abolish("oppertunit{y,ies}", "opp{or}tunit{}")
Abolish("opposible", "opposable")
Abolish("oppasite", "opposite")
Abolish("oppos{ate,it}", "opposite")
Abolish("orginiz{e,ed,ation}", "organiz{}")
Abolish("orgi{n,nal}", "origi{}")
Abolish("o{hte,teh}r", "other")
Abolish("otu", "out")
Abolish("outof", "out of")
Abolish("overthe", "over the")
Abolish("oxident", "oxidant")
-- P
Abolish("palistian", "Palestinian")
Abolish("palistinia{n,ns}", "Palestinia{}")
Abolish("papaer", "paper")
Abolish("parliment", "parliament")
Abolish("partof", "part of")
Abolish("paymetn", "payment")
Abolish("paymetns", "payments")
Abolish("peo{lpe,pel}", "people")
Abolish("poeple", "people")
Abolish("percent{of,to}", "percent {}")
Abolish("performence", "performance")
Abolish("perh{asp,pas}", "perhaps")
Abolish("perm{ana,ani,ena,ene,eni,ina,ine,ini}nt", "permanent")
Abolish("perm{ana,ani,ena,ene,eni,ina,ine,ini}ntly", "permanently")
Abolish("permen{a,e,i}nt", "permanent")
Abolish("permin{a,e,i}ntly", "permanently")
Abolish("persistan{ce,t,tly}", "persisten{}")
Abolish("personalyl", "personally")
Abolish("pciture", "picture")
Abolish("peic{e,es}", "piec{}")
Abolish("pleasent", "pleasant")
Abolish("postition", "position")
Abolish("psoitio{n,ned,nally,ns}", "positio{}")
Abolish("possable", "possible")
Abolish("potentialy", "potentially")
Abolish("pwoer", "power")
Abolish("pregnent", "pregnant")
Abolish("presance", "presence")
Abolish("porble{m,ms}", "problem{}")
Abolish("ptogress", "progress")
Abolish("prominant{t,tly}", "prominen{}")
Abolish("prot{e,o}ge", "protégé")
Abolish("porvide", "provide")
Abolish("puting", "putting")
-- Q
Abolish("quate{r,rs,rly}", "quarte{}")
Abolish("que{tio,toi,sio,oi,stio,stoi}n", "question")
Abolish("que{tions,tioms,tiosn,toins,toims,toisn,sions,sioms,siosn,oins,oims,oisn,stioms,stiosn,stoins,stoims,stoisn}", "questions") 
-- R
Abolish("reimplimen{t,ts,ting,ted,tation}", "reimplemen{}")
Abolish("realize", "realise")
Abolish("realyl", "really")
Abolish("receiev{e,ed,ing}", "receiv{}")
Abolish("reciev{e,ed,ing}", "receiv{}")
Abolish("recieve", "receive")
Abolish("reconize", "recognize")
Abolish("re{c,cc}o{m,mm}end", "recommend")
Abolish("reommend", "recommend")
Abolish("recomend{,ation,ations,ed,s}", "recommend{}")
Abolish("rec{co,com,o}mend{,s,ed,ing,ation}", "rec{om}mend{}")
Abolish("recrod", "record")
Abolish("reflektion", "reflection")
Abolish("referes{h,hes}", "refres{}")
Abolish("releven{ce,cy,t,tly}", "relevan{}")
Abolish("religous", "religious")
Abolish("reluctent", "reluctant")
Abolish("remeber", "remember")
Abolish("REmove", "Remove")
Abolish("represnt", "represent")
Abolish("represent{ativ,ive}s", "representatives")
Abolish("represetned", "represented")
Abolish("reproducable", "reproducible")
Abolish("reserach", "research")
Abolish("resollution", "resolution")
Abolish("resouc{e,es}", "resourc{}")
Abolish("resorces", "resources")
Abolish("respom{d,se}", "respon{}")
Abolish("responce", "response")
Abolish("responsab{le,ility}", "responsib")
Abolish("responsib{le,ility}", "responsib")
Abolish("rest{arau,uara}nt", "restaurant")
Abolish("restraun{t,ts}", "restauran{}")
Abolish("reult", "result")
Abolish("revei{w,ws,wed,wing}", "revie{}")
Abolish("reivew", "review")
Abolish("rythm", "rhythm")
Abolish("rumers", "rumors")
-- S
Abolish("said{he,it,that,the}", "said {}")
Abolish("smae", "same")
Abolish("scedul{e,es,ed,ing,er}", "schedul{}")
Abolish("shcool", "school")
Abolish("seance", "séance")
Abolish("seach", "search")
Abolish("secratary", "secretary")
Abolish("sectino", "section")
Abolish("sercurit", "security")
Abolish("segumen{t,ts,ted,tation}", "segmen{}")
Abolish("selectoin", "selection")
Abolish("selectino", "selection")
Abolish("sefl", "self")
Abolish("sentance", "sentence")
Abolish("seperat{e,es,ed,ing,ely,ion,ions,or}", "separat{}")
Abolish("sep{are,er}ate", "separate")
Abolish("seh", "she")
Abolish("shesaid", "she said")
Abolish("shineing", "shining")
Abolish("shiped", "shipped")
Abolish("shoudl", "should")
Abolish("shoul{d,de}nt", "shouldn’t")
Abolish("sohw", "show")
Abolish("showinf", "showing")
Abolish("signifacnt", "significant")
Abolish("sim{al,ili}ar", "similar")
Abolish("simpyl", "simply")
Abolish("sincerly", "sincerely")
Abolish("snip{e,p}t", "snippet")
Abolish("soical", "social")
Abolish("s{moe,oem,}", "some")
Abolish("somet{hign,ing,hing,ting}", "something")
Abolish("somtimes", "sometimes")
Abolish("somewaht", "somewhat")
Abolish("soudns", "sounds")
Abolish("soudn", "sound")
Abolish("specifical{y,yl}", "specifically")
Abolish("speach", "speech")
Abolish("stnad", "stand")
Abolish("statments", "statements")
Abolish("statment", "statement")
Abolish("sitll", "still")
Abolish("stpo", "stop")
Abolish("sto{pry,yr}", "story")
Abolish("stroy", "story")
Abolish("strentgh", "strength")
Abolish("strug{gel,le}", "struggle")
Abolish("studnet", "student")
Abolish("sucess", "success")
Abolish("sucessfull", "successful")
Abolish("successful{y,yl}", "successfully")
Abolish("sufficiant", "sufficient")
Abolish("sup{o,pos}sed", "supposed")
Abolish("suppossed", "supposed")
Abolish("supris{e,ed,es,ing}", "surpris{}")
Abolish("surprice", "surprise")
Abolish("swiming", "swimming")
-- T
Abolish("tka{e,es,ing}", "tak{}")
Abolish("talekd", "talked")
Abolish("t{al,la}kign", "talking")
Abolish("tecnica{l,lly}", "technica{}")
Abolish("esting", "testing")
Abolish("TEsting", "Testing")
Abolish("textexp{a,e}nder", "TextExpander")
Abolish("tahn", "than")
Abolish("thansk", "thanks")
Abolish("ta{ht,th}", "that")
Abolish("thatthe", "that the")
Abolish("th{gat,ta}", "that")
Abolish("tyhat", "that")
Abolish("tha{ts,st}", "that’s")
Abolish("the{new,same,two,government,first,company}", "the {}")
Abolish("t{j,gh,jh}e", "the")
Abolish("hte", "the")
Abolish("t{the,eh,yhe}", "the")
Abolish("teh", "the")
Abolish("tehn", "then")
Abolish("th{eri,ier}", "their")
Abolish("themsel{f,fs}", "themselves")
Abolish("htere", "there")
Abolish("htese", "these")
Abolish("{htey,tehy}", "they")
Abolish("the{y,yve}", "they’{}")
Abolish("hting", "thing")
Abolish("thni{g,gs}", "thin{}")
Abolish("thigsn", "things")
Abolish("{htink,thikn}", "think")
Abolish("htis", "this")
Abolish("t{hsi,ihs,ghis}", "this")
Abolish("thisyear", "this year")
Abolish("thn{a,e}", "th{}n")
Abolish("th{soe,ones}", "those")
Abolish("threatend", "threatened")
Abolish("timne", "time")
Abolish("ot", "to")
Abolish("tothe", "to the")
Abolish("todya", "today")
Abolish("t{iogeth,ogeht}er", "together")
Abolish("tomorow", "tomorrow")
Abolish("ton{gih,ihg}t", "tonight")
Abolish("torben", "Torben")
Abolish("total{y,yl}", "totally")
Abolish("towrad", "toward")
Abolish("traditionalyl", "traditionally")
Abolish("transfered", "transferred")
Abolish("tryed", "tried")
Abolish("tru{el,le}y", "truly")
Abolish("termoil", "turmoil")
Abolish("tweetes", "tweets")
Abolish("ype", "type")
Abolish("{t,y}po", "typo")
-- U
Abolish("udnerst{an,na}d", "understand")
Abolish("unnec{ce,ces,e}sary", "necessary")
Abolish("unnec{ce,ces,e}sary", "necessarily")
Abolish("UnitedStates", "United States")
Abolish("unliek", "unlike")
Abolish("unpleasently", "unpleasantly")
Abolish("unorgi{n,nal}", "unorigi{}")
Abolish("untill{,l}", "until")
Abolish("useing", "using")
Abolish("usualyl", "usually")
-- V
Abolish("{veyr,vrey}", "very")
Abolish("virtualyl", "virtually")
Abolish("vodi", "void")
Abolish("vulnerible", "vulnerable")
-- W
Abolish("watn", "want")
Abolish("wna{t,ts,ted}", "wan{}")
Abolish("warrent", "warrant")
Abolish("wasnt", "wasn’t")
Abolish("wya", "way")
Abolish("wierd", "weird")
Abolish("werre", "were")
Abolish("w{aht,hta, aht}", "what")
Abolish("wehn", "when")
Abolish("wherre", "where")
Abolish("{hwich,whcih,whic,whihc,wihch}", "which")
Abolish("woh", "who")
Abolish("wohle", "whole")
Abolish("witdh", "width")
Abolish("wief", "wife")
Abolish("{iw,wiu}ll", "will")
Abolish("windoes", "windows")
Abolish("iwth", "with")
Abolish("w{iht,ithe,tih}", "with")
Abolish("with{a,be,the}", "with {}")
Abolish("wrod", "word")
Abolish("{owrk,wokr}", "work")
Abolish("wroking", "working")
Abolish("{owuld,woudl,wuould}", "would")
Abolish("wouldbe", "would be")
Abolish("wouldnt", "wouldn’t")
Abolish("{wriet,rwite}", "write")
Abolish("writting", "writing")
Abolish("wroet", "wrote")
-- X
-- Y
Abolish("yera", "year")
Abolish("yer{as,sa}", "years")
Abolish("tes", "yes")
Abolish("eyt", "yet")
Abolish("y{tou,oiu}", "you")
Abolish("yuo{,r}", "you{}")
Abolish("youare", "you are")
Abolish("you{re,ve}", "you'{}")
-- Z
